version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio-server
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # Порт API
      - "9001:9001" # Порт Console
    environment:
      MINIO_ROOT_USER:   
      MINIO_ROOT_PASSWORD:  
    volumes:
      - ./miniodata:/data 
    restart: always

volumes:
  miniodata: