version: '3.8'

services:
  db:
    image: postgres:16-bookworm
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=  
      - POSTGRES_PASSWORD=  
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: