// <auto-generated />
using System;
using DBDAnalytics.MatchService.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBDAnalytics.MatchService.Infrastructure.EF.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20251001091052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerAddon", b =>
                {
                    b.Property<Guid>("KillerPerformanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("KillerPerformanceId");

                    b.Property<Guid>("AddonId")
                        .HasColumnType("uuid")
                        .HasColumnName("AddonId");

                    b.HasKey("KillerPerformanceId", "AddonId");

                    b.ToTable("KillerAddons", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerAssociationId");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("Experience");

                    b.Property<bool>("IsAnonymousMode")
                        .HasColumnType("boolean")
                        .HasColumnName("IsAnonymousMode");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("IsBot");

                    b.Property<Guid>("KillerId")
                        .HasColumnType("uuid")
                        .HasColumnName("KillerId");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("MatchId");

                    b.Property<int>("NumberBloodDrops")
                        .HasColumnType("integer")
                        .HasColumnName("NumberBloodDrops");

                    b.Property<Guid>("OfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("OfferingId");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("PlatformId");

                    b.Property<int>("Prestige")
                        .HasColumnType("integer")
                        .HasColumnName("Prestige");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("Score");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("KillerPerformances", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerPerk", b =>
                {
                    b.Property<Guid>("KillerPerformanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("KillerPerformanceId");

                    b.Property<Guid>("PerkId")
                        .HasColumnType("uuid")
                        .HasColumnName("PerkId");

                    b.HasKey("KillerPerformanceId", "PerkId");

                    b.ToTable("KillerPerks", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("CountHooks")
                        .HasColumnType("integer")
                        .HasColumnName("CountHooks");

                    b.Property<int>("CountKills")
                        .HasColumnType("integer")
                        .HasColumnName("CountKills");

                    b.Property<int>("CountRecentGenerators")
                        .HasColumnType("integer")
                        .HasColumnName("CountRecentGenerators");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("Duration");

                    b.Property<int>("GameEventId")
                        .HasColumnType("integer")
                        .HasColumnName("GameEventId");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer")
                        .HasColumnName("GameModeId");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("MapId");

                    b.Property<int>("PatchId")
                        .HasColumnType("integer")
                        .HasColumnName("PatchId");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<int>("WhoPlacedMapId")
                        .HasColumnType("integer")
                        .HasColumnName("WhoPlacedMapId");

                    b.Property<int>("WhoPlacedMapWinId")
                        .HasColumnType("integer")
                        .HasColumnName("WhoPlacedMapWinId");

                    b.HasKey("Id");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ItemId");

                    b.Property<Guid>("SurvivorPerformanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SurvivorPerformanceId");

                    b.HasKey("Id");

                    b.HasIndex("SurvivorPerformanceId");

                    b.ToTable("SurvivorItems", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorItemAddon", b =>
                {
                    b.Property<Guid>("SurvivorItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("SurvivorItemId");

                    b.Property<Guid>("AddonId")
                        .HasColumnType("uuid")
                        .HasColumnName("AddonId");

                    b.HasKey("SurvivorItemId", "AddonId");

                    b.ToTable("SurvivorItemAddons", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerAssociationId");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("Experience");

                    b.Property<bool>("IsAnonymousMode")
                        .HasColumnType("boolean")
                        .HasColumnName("IsAnonymousMode");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("IsBot");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("MatchId");

                    b.Property<int>("NumberBloodDrops")
                        .HasColumnType("integer")
                        .HasColumnName("NumberBloodDrops");

                    b.Property<Guid>("OfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("OfferingId");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("PlatformId");

                    b.Property<int>("Prestige")
                        .HasColumnType("integer")
                        .HasColumnName("Prestige");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("Score");

                    b.Property<Guid>("SurvivorId")
                        .HasColumnType("uuid")
                        .HasColumnName("SurvivorId");

                    b.Property<int>("TypeDeathId")
                        .HasColumnType("integer")
                        .HasColumnName("TypeDeathId");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("SurvivorPerformances", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorPerk", b =>
                {
                    b.Property<Guid>("SurvivorPerformanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SurvivorPerformanceId");

                    b.Property<Guid>("PerkId")
                        .HasColumnType("uuid")
                        .HasColumnName("PerkId");

                    b.HasKey("SurvivorPerformanceId", "PerkId");

                    b.ToTable("SurvivorPerks", (string)null);
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerAddon", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.KillerPerformance", null)
                        .WithMany("Addons")
                        .HasForeignKey("KillerPerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerPerformance", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.Match", null)
                        .WithMany("KillerPerformances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerPerk", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.KillerPerformance", null)
                        .WithMany("Perks")
                        .HasForeignKey("KillerPerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorItem", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.SurvivorPerformance", null)
                        .WithMany("Items")
                        .HasForeignKey("SurvivorPerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorItemAddon", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.SurvivorItem", null)
                        .WithMany("Addons")
                        .HasForeignKey("SurvivorItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorPerformance", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.Match", null)
                        .WithMany("SurvivorPerformances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorPerk", b =>
                {
                    b.HasOne("DBDAnalytics.MatchService.Domain.Models.SurvivorPerformance", null)
                        .WithMany("Perks")
                        .HasForeignKey("SurvivorPerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.KillerPerformance", b =>
                {
                    b.Navigation("Addons");

                    b.Navigation("Perks");
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.Match", b =>
                {
                    b.Navigation("KillerPerformances");

                    b.Navigation("SurvivorPerformances");
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorItem", b =>
                {
                    b.Navigation("Addons");
                });

            modelBuilder.Entity("DBDAnalytics.MatchService.Domain.Models.SurvivorPerformance", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Perks");
                });
#pragma warning restore 612, 618
        }
    }
}
